### ISSUE TITLE
Question: ViewModel transform(input:) -> SearchViewModel.Output 

### ISSUE THREAD

**Issue by amadeu01** [tailec/ios-architecture#5]
Could you explain more about this implementation.

`func transform(input: SearchViewModel.Input) -> SearchViewModel.Output {`

I could not understand well. The `ViewModel` is some sort of pipeline that for an input it generates one output?

**Comment by tailec** [comment]
Yeah exactly.

It's just a way of describing bindings between VM and VC without using Subjects.
Bear in mind, a view model with `ViewModelType` protocol will only work with view controllers that are able to create all inputs **at the same time** (usually in `viewDidLoad` lifecycle method).
